const list=[
    {
        id:1,
        name:"toyota",
        img1:"https://5.imimg.com/data5/WC/YW/GLADMIN-59169454/toyota-innova-1000x1000.png",
        price:"150000",
        fueltype:"Diesel",
        mileage:"15.1KM/L",
        capacity:"55.0/65.0L",
        maxpower:"148,150 bhp",
        rating:4,
        amount: 1,
        desc:"Laxmi Innova Car Toy for Kids, Vehicle Toys for Boys, Car Models Toys, Kids Playing Items Indoor [RED, Blue, Golden, Silver, Pack of 1"
    },
    {
        id:2,
        name:"breeza",
        img1:"https://5.imimg.com/data5/IX/JA/GLADMIN-66473958/maruti-vitara-brezza-car-1000x1000.png",
        price:"140000",
        fueltype:"Diesel",
        mileage:"14.1KM/L",
        capacity:"52.0/65.0L",
        maxpower:"148,150 bhp",
        rating:3,
        amount: 1,
        desc:"Laxmi Innova Car Toy for Kids, Vehicle Toys for Boys, Car Models Toys, Kids Playing Items Indoor [RED, Blue, Golden, Silver, Pack of 1"
    },
    {
        id:3,
        name:"Mercedes",
        price:"150000",
        img1:"https://imgd.aeplcdn.com/664x374/n/cw/ec/142603/g-class-right-front-three-quarter.jpeg?isig=0&q=80",
        fueltype:"Diesel",
        mileage:"15.1KM/L",
        capacity:"55.0/65.0L",
        maxpower:"148,150 bhp",
        rating:5,
        amount: 1,
        desc:"Laxmi Innova Car Toy for Kids, Vehicle Toys for Boys, Car Models Toys, Kids Playing Items Indoor [RED, Blue, Golden, Silver, Pack of 1"
    },
    {
        id: 4,
        name: "Toyota",
        img1: "https://5.imimg.com/data5/WC/YW/GLADMIN-59169454/toyota-innova-1000x1000.png",
        price: "150000",
        fueltype: "Diesel",
        mileage: "15.1KM/L",
        capacity: "55.0/65.0L",
        maxpower: "148,150 bhp",
        rating: 4,
        amount: 1,
        desc: "Laxmi Innova Car Toy for Kids, Vehicle Toys for Boys, Car Models Toys, Kids Playing Items Indoor [RED, Blue, Golden, Silver, Pack of 1"
    },
    {
        "id": 2,
        "name": "Honda",
        "img1": "https://images.dealer.com/ddc/vehicles/2024/Honda/Pilot/SUV/trim_Touring_c6e486/color/Platinum%20White%20Pearl-WY-235%2C234%2C231-640-en_US.jpg?impolicy=downsize_bkpt&imdensity=1&w=520",
        "price": "140000",
        "fueltype": "Petrol",   
        "mileage": "17.4KM/L",
        "capacity": "40.0/50.0L",
        "maxpower": "119 bhp",
        "rating": 4.5,
        amount: 1,
        "desc": "The Honda City has 1 Petrol Engine on offer. The Petrol engine is 1498 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the City"
    },
    {
        "i": 3,
        "name": "Ford",
        "img1": "https://development.bookyourcar.co.in/uploads/models/80/ford-ecosport-diamond-white.jpg",
        "price": "200000",
        "fueltype": "Petrol",
        "mileage": "12.5KM/L",
        "capacity": "60.0L",
        "maxpower": "450 bhp",
        "rating": 4.8,
        amount: 1,
        "desc": "Ford Mustang, an iconic sports car known for its powerful performance."
    },
    {
        "id": 4,
        "name": "BMW",
        "img1": "https://imgd-ct.aeplcdn.com/664x415/n/cw/ec/176131/m4-competition-right-front-three-quarter.jpeg?isig=0&q=80",
        "price": "350000",
        "fueltype": "Diesel",
        "mileage": "20.0KM/L",
        "capacity": "65.0L",
        "maxpower": "382 bhp",
        "rating": 4.9,
        amount: 1,
        "desc": "BMW 3 Series, a luxury sedan that combines performance and style."
    },
    {
        "id": 5,
        "name": "Mercedes",
        "img1": "https://cdni.autocarindia.com/Utils/ImageResizerV2.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Mercedes-Benz-GLC-110820231043.jpg&w=373&h=245&q=75&c=1",
        "price": "320000",
        "fueltype": "Petrol",
        "mileage": "18.0KM/L",
        "capacity": "50.0L",
        "maxpower": "221 bhp",
        "rating": 4.7,
        amount: 1,
        
        "desc": "Mercedes-Benz A-Class, a compact luxury car with advanced features."
    },
    {
        "id": 6,
        "name": "Audi",
        "img1": "https://uploads.audi-mediacenter.com/system/production/car_families/28/photos/2515d9eaa0b2ee3ac083e20b3b88bd2d5419ea9d/web_1440_Audi_R8.jpg?1698934944",
        "price": "330000",
        "fueltype": "Diesel",
        "mileage": "22.0KM/L",
        "capacity": "58.0L",
        "maxpower": "190 bhp",
        "rating": 4.6,
        amount: 1,
        "desc": "Audi A4, a stylish and technologically advanced luxury sedan."
    },
    {
        "id": 7,
        "name": "Hyundai",
        "img1": "https://imgd.aeplcdn.com/664x374/n/cw/ec/139133/aura-exterior-right-front-three-quarter-5.jpeg?isig=0&q=80",
        "price": "120000",
        "fueltype": "Petrol",
        "mileage": "19.0KM/L",
        "capacity": "45.0L",
        "maxpower": "83 bhp",
        "rating": 4.2,
        amount: 1,
        "desc": "Hyundai i20, a compact hatchback offering efficiency and modern design."
    },
    {
        "id": 8,
        "name": "Kia",
        "img1": "https://imgd-ct.aeplcdn.com/664x415/n/cw/ec/174327/carens-right-front-three-quarter-2.jpeg?isig=0&q=80",
        "price": "160000",
        "fueltype": "Diesel",
        "mileage": "20.8KM/L",
        "capacity": "50.0L",
        "maxpower": "138 bhp",
        "rating": 4.3,
        amount: 1,
        "desc": "Kia Seltos, a compact SUV known for its features and versatility."
    },
    {
        "id": 9,
        "name": "Nissan",
        "img1": "https://global.nissannews.com/page-0a3c17000171b2fc662bfd35f7006290/attachment/289a38bc2a9a3d112a1dd8b4e275330af39d2555",
        "price": "150000",
        "fueltype": "Petrol",
        "mileage": "14.0KM/L",
        "capacity": "50.0L",
        "maxpower": "156 bhp",
        "rating": 4.1,
        amount: 1,
        "desc": "Nissan Kicks, a stylish compact SUV with advanced safety features."
    },
    {
        id: 11,
        name: "Chevrolet",
        img1: "https://imgd.aeplcdn.com/664x374/ec/A4/30/9790/img/m/Chevrolet-Captiva-Right-Front-Three-Quarter-49909_ol.jpg?v=201711021421&q=80",
        price: "210000",
        fueltype: "Electric",
        mileage: "259 miles",
        capacity: "66 kWh",
        maxpower: "200 bhp",
        rating: 4.5,
        amount: 1,
        desc: "The Chevrolet brand was on sale in India. It’s famous for its Chevrolet Cruze, Chevrolet Enjoy, Chevrolet Tavera, Chevrolet Trailblazer, Chevrolet Beat models. The manufacturer 13.95 Lakh. There is no official word from the manufacturer on its re-entry into the Indian market."
    },
    {
        id: 12,
        name: "Mazda",
        img1: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Mazda/Mazda-Miata/2750/1562665396308/front-left-side-47.jpg?impolicy=resize&imwidth=480",
        price: "250000",
        fueltype: "Petrol",
        mileage: "26.0KM/L",
        capacity: "45.0L",
        maxpower: "181 bhp",
        rating: 4.7,
        amount: 1,
        desc: "Mazda is consistently ranked among the most reliable brands. For spirited drives or cruising, these reliable coupes, sedans, and roadsters are good choices. Consumer Reports and the IIHS name safe, reliable new cars and SUVs that are smart choices for teens."
    },
    {
        id: 13,
        name: "Subaru",
        img1: "https://s7d1.scene7.com/is/image/scom/OBK_default_nav-5?$400j$",
        price: "180000",
        fueltype: "Petrol",
        mileage: "20.8KM/L",
        capacity: "50.0L",
        maxpower: "152 bhp",
        rating: 4.4,
        amount: 1,
        desc: "Subarus certainly rank high in safety, cost of ownership, and dependability, with respectable fuel efficiency and average repair cost ratings as well."
    },
    {
        id: 14,
        name: "Volvo",
        img1: "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/XC90ModelImage.jpg&w=872&h=578&q=75&c=1",
        price: "350000",
        fueltype: "Diesel",
        mileage: "21.7KM/L",
        capacity: "60.0L",
        maxpower: "250 bhp",
        rating: 4.8,
        amount: 1,
        desc: "The price of Volvo S90, a 5 seater Sedan, starts from of Rs. 68.25 Lakh. It is available in 1 variant, with an engine of 1969 cc and a choice of 1 transmission: Automatic. S90 has an NCAP rating of 5 stars and comes with 7 airbags."
    },
   
    {
        id: 15,
        name: "Jaguar",
        img1: "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Jaguar-F-Pace-100520231603.jpghttps://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Jaguar-F-Pace-100520231603.jpg",
        price: "370000",
        fueltype: "Diesel",
        mileage: "19.5KM/L",
        capacity: "55.0L",
        maxpower: "247 bhp",
        rating: 4.8,
        amount: 1,
        desc: "Jaguar car price starts at Rs 72.90 Lakh for the cheapest model which is F-Pace and the price of most expensive model, which is I-Pace starts at Rs 1.26 Crore. Jaguar offers 2 car models in India, including 2 cars in SUV category."
    },
    {
        id: 16,
        name: "Tesla",
        img1: "https://media.ed.edmunds-media.com/tesla/model-s/2024/oem/2024_tesla_model-s_sedan_plaid_fq_oem_1_1600.jpg",
        price: "800000",
        fueltype: "Electric",
        mileage: "348 miles",
        capacity: "100 kWh",
        maxpower: "1020 bhp",
        rating: 4.9,
        amount: 1,
        desc: "The Tesla brand is well-known for its Tesla Cybertruck, Tesla Model 2, Tesla Model 3, Tesla Model S, Tesla Model X cars majorly. The first offering from the Tesla brand is likely to tug it out in the Pickup Trucks segment."
    },
    {
        id: 17,
        name: "Porsche",
        img1: "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Porsche-Macan-220620221545.jpg&w=350&h=251&q=91&c=1",
        price: "1100000",
        fueltype: "Petrol",
        mileage: "10.5KM/L",
        capacity: "64.0L",
        maxpower: "640 bhp",
        rating: 4.9,
        amount: 1,
        desc: "Porsche car price starts at Rs 88.06 Lakh for the cheapest model which is Macan and the price of most expensive model, which is 911 starts at Rs 1.86 Crore. Porsche offers 9 car models in India, including 3 cars in SUV category, 2 cars in Sedan category, 3 cars in Coupe category, 1 car in Station Wagon category."
    },
    {
        id: 18,
        name: "Lexus",
        img1: "https://imgd-ct.aeplcdn.com/664x415/n/cw/ec/139465/rx-exterior-right-front-three-quarter-6.jpeg?isig=0&q=80",
        price: "750000",
        fueltype: "Hybrid",
        mileage: "15.2KM/L",
        capacity: "82.0L",
        maxpower: "354 bhp",
        rating: 4.7,
        amount: 1,
        desc: "Lexus car price starts at Rs 63.10 Lakh for the cheapest model which is ES and the price of most expensive model, which is LX starts at Rs 2.82 Crore. Lexus offers 6 car models in India, including 3 cars in SUV category, 1 car in Sedan category, 1 car in MUV category, 1 car in Coupe category."
    },
    {
        id: 19,
        name: "Ferrari",
        img1: "https://imgd-ct.aeplcdn.com/1280x720/cw/ec/21101/Ferrari-488-Right-Front-Three-Quarter-61997.jpg?wm=0&t=163306467&t=163306467&q=80",
        price: "4500000",
        fueltype: "Petrol",
        mileage: "8.5KM/L",
        capacity: "92.0L",
        maxpower: "789 bhp",
        rating: 5,
        amount: 1,
        desc: "Ferrari is famous for manufacturing world class sports car across the globe. The compan is based in Maranello, Italy, it was founded in the year 1929 by Enzo Ferrari as Scuderia Ferrari. Initially the company was involved in manufacturing race cars along with sponsoring drivers."
    },
    {
        id: 20,
        name: "Lamborghini",
        img1: "https://imgd.aeplcdn.com/272x153/n/cw/ec/164543/revuelto-exterior-right-front-three-quarter-2.jpeg?isig=0&q=80",
        price: "5000000",
        fueltype: "Petrol",
        mileage: "7.5KM/L",
        capacity: "85.0L",
        maxpower: "770 bhp",
        rating: 5,
        amount: 1,
        desc: "Lamborghini car price starts at Rs 3.22 Crore for the cheapest model which is Huracan Evo and the price of most expensive model, which is Revuelto starts at Rs 8.89 Crore. Lamborghini offers 8 car models in India, including 2 cars in SUV category, 1 car in Convertible category, 5 cars in Coupe category."
    },
    {
        id: 21,
        name: "Maserati",
        img1: "https://imgd-ct.aeplcdn.com/664x415/cw/ec/19431/Maserati-GranTurismo-Exterior-138060.jpg?wm=0&q=80",
        price: "700000",
        fueltype: "Petrol",
        mileage: "10.7KM/L",
        capacity: "80.0L",
        maxpower: "345 bhp",
        rating: 4.7,
        amount: 1,
        desc: "Maserati car price starts at Rs. 1.20 Crore and goes upto Rs. 3.65 Crore (Avg. ex-showroom). The prices for the top 4 popular Maserati Cars are: Maserati Ghibli Price is Rs. 1.20 Crore, Maserati Quattroporte Price is Rs. 1.80 Crore, Maserati MC20 Price is Rs. 3.65 Crore and Maserati Levante Price is Rs. 1.45 Crore."
    },
    {
        id: 22,
        name: "Bentley",
        img1: "https://imgd.aeplcdn.com/1200x900/cw/ec/40239/Bentley-Continental-GT-Exterior-158571.jpg?wm=0&q=80",
        price: "6000000",
        fueltype: "Petrol",
        mileage: "6.8KM/L",
        capacity: "96.0L",
        maxpower: "530 bhp",
        rating: 5,
        amount: 1,
        desc: "The price of Bentley cars in India starts from ₹ 5 Cr for the Bentayga while the most expensive Bentley car in India one is the Flying Spur with a price of ₹ 7.60 Cr. The newest model in the Bentley line-up is the Flying Spur with a price tag of ₹ 5.25 - 7.60 Cr."
    },
    {
        id: 23,
       name: "Rolls-Royce",
       img1: "https://imgd.aeplcdn.com/1280x720/n/cw/ec/30181/phantom-exterior-right-front-three-quarter.jpeg?isig=0&q=80",
        price: "9000000",
        fueltype: "Petrol",
        mileage: "5.9KM/L",
        capacity: "100.0L",
        maxpower: "563 bhp",
        amount: 1,

        rating: 5,desc: "The price of Rolls-Royce cars in India starts from ₹ 6.95 Cr for the Cullinan while the most expensive Rolls-Royce car in India one is the Phantom with a price of ₹ 10.48 Cr. The newest model in the Rolls-Royce line-up is the Spectre with a price tag of ₹ 7.50 Cr."
    },
    {
        id: 24,
        name: "Aston Martin",
        img1: "https://media.zigcdn.com/media/model/2023/Feb/db11-8_360x240.jpg",
        price: "3500000",
        fueltype: "Petrol",
        mileage: "8.9KM/L",
        capacity: "90.0L",
        maxpower: "580 bhp",
        rating: 4.9,
        amount: 1,
        desc: "Aston Martin car price starts at Rs 3.29 Crore for the cheapest model which is DB11 and the price of most expensive model, which is DB12 starts at Rs 4.59 Crore. Aston Martin offers 4 car models in India, including 1 car in SUV category, 1 car in Convertible category, 2 cars in Coupe category."
    },
    {
        id: 25,
        name: "Alfa Romeo",
        img1: "https://car-images.bauersecure.com/wp-images/161115/alfa_giulia_bev.jpg",
        price: "450000",
        fueltype: "Petrol",
        mileage: "17.8KM/L",
        capacity: "58.0L",
        maxpower: "280 bhp",
        rating: 4.6,
        amount: 1,
        desc: "Its first car was the 1910 24 HP, designed by Giuseppe Merosi. Alfa ventured into motor racing, with drivers Franchini and Ronzoni competing in the 1911 Targa Florio with two 24-hp models."
    },
    {
        id: 26,
        name: "Land Rover",
        img1: "https://imgd-ct.aeplcdn.com/664x415/n/cw/ec/108651/range-rover-right-front-three-quarter.jpeg?isig=0&q=80",
        price: "550000",
        fueltype: "Diesel",
        mileage: "14.7KM/L",
        capacity: "85.0L",
        maxpower: "296 bhp",
        rating: 4.8,
        amount: 1,
        desc: "Land Rover car price starts at Rs 67.90 Lakh for the cheapest model which is Range Rover Evoque and the price of most expensive model, which is Range Rover starts at Rs 2.39 Crore. Land Rover offers 7 car models in India, including 7 cars in SUV category."
    },
    {
        id: 27,
        name: "Jeep",
        img1: "https://static.autox.com/uploads/cars/2024/04/jeep-wrangler.jpg",
        price: "450000",
        fueltype: "Petrol",
        mileage: "13.0KM/L",
        capacity: "70.0L",
        maxpower: "285 bhp",
        rating: 4.5,
        amount: 1,
        desc: "Jeep car price starts at Rs 20.69 Lakh for the cheapest model which is Compass and the price of most expensive model, which is Grand Cherokee starts at Rs 80.49 Lakh. Jeep offers 4 car models in India, including 4 cars in SUV category. "
    },
    {
        id: 28,
        name: "Mitsubishi",
        img1: "https://imgd.aeplcdn.com/370x208/cw/ec/23799/Mitsubishi-Montero-Right-Front-Three-Quarter-74529.jpg?wm=0",
        price: "220000",
        fueltype: "Petrol",
        mileage: "15.2KM/L",
        capacity : "63.0L",
        maxpower: "148 bhp",
        rating: 4.3,
        amount: 1,
        desc: "Mitsubishi Motors, founded in 1970, is a Japanese automobile manufacturer. Currently, Nissan owns one-third or 34% of the Mitsubishi brand which is thus a part of the Renault-Nissan-Mitsubishi alliance. "
    },
    
]

export default list;